dataframes:
  data_EB:
    df_data_EB_train.h5
  data_EE:
    df_data_EE_train.h5
  mc_EB:
    df_mc_EB_train.h5
  mc_EE:
    df_mc_EE_train.h5

variables:
  ['probeCovarianceIeIp','probeS4','probeR9','probePhiWidth_Sc','probeSigmaIeIe','probeEtaWidth_Sc']

year:
  2018

workDir:
  /work/xchang/tmp/tnp

weightsDir:
  /work/xchang/weights/2018
