data:
  base_dir:
    "/work/xchang/root_files/tnp_original/test_data_UL18"
  file_tmpl:
    "output_EGamma_alesauva-UL2018_0-10_6_4-v0-Run2018{}-12Nov2019_UL2018-{}-981b04a73c9458401b9ffd78fdd24189_USER_{}.root"
  number:
    500
  tree_path:
    "tagAndProbeDumper/trees/Data_13TeV_All"
  output_file:
    "/work/xchang/root_files/tnp_merged_outputs/2018/first_test/outputData.root"
  runs_id:
    A: "v2"
    B: "v2"
    C: "v2"
    D: "v4"

mc:
  base_dir:
    "/work/xchang/root_files/tnp_original/test_mc_UL18"
  file_tmpl:
    "output_DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8_alesauva-UL2018_0-10_6_4-v0-RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v2-b5e482a1b1e11b6e5da123f4bf46db27_USER_{}.root"
  number:
    500
  tree_path:
    "tagAndProbeDumper/trees/DYJetsToLL_amcatnloFXFX_13TeV_All"
  output_file:
    "/work/xchang/root_files/tnp_merged_outputs/2018/first_test/outputMC.root"


